"""Added checked status at ticket

Revision ID: 08711ce48372
Revises: de5b217ed07a
Create Date: 2023-05-15 14:46:54.185038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08711ce48372'
down_revision = 'de5b217ed07a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('capacity', sa.Integer(), nullable=True))
    op.drop_constraint('event_admin_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'admin_id')
    op.add_column('ticket', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'checked')
    op.add_column('event', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_admin_id_fkey', 'event', 'users', ['admin_id'], ['id'])
    op.drop_column('event', 'capacity')
    # ### end Alembic commands ###
