"""Fix typo in foreign key

Revision ID: 08c3fb51c857
Revises: a8bfd9164bf1
Create Date: 2023-05-10 22:33:33.666345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c3fb51c857'
down_revision = 'a8bfd9164bf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usereventbooking_userid_fkey', 'usereventbooking', type_='foreignkey')
    op.create_foreign_key(None, 'usereventbooking', 'users', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usereventbooking', type_='foreignkey')
    op.create_foreign_key('usereventbooking_userid_fkey', 'usereventbooking', 'venue', ['userid'], ['id'])
    # ### end Alembic commands ###
