"""Commit Message

Revision ID: 10cf619a331a
Revises: daf4f57ecdb5
Create Date: 2023-05-14 19:37:32.834752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cf619a331a'
down_revision = 'daf4f57ecdb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
