"""add logo to admin

Revision ID: 12ba374836ce
Revises: 872fbeee0e3e
Create Date: 2023-05-22 23:33:11.622990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ba374836ce'
down_revision = '872fbeee0e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'logo')
    # ### end Alembic commands ###
