"""Commit Message

Revision ID: 132718f75162
Revises: 6c73fd48143a
Create Date: 2023-05-14 12:33:52.504454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132718f75162'
down_revision = '6c73fd48143a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
