"""Fix missing revision

Revision ID: 13abbf30cd2a
Revises: 6b20497da0ba
Create Date: 2023-05-15 14:36:51.656765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13abbf30cd2a'
down_revision = '6b20497da0ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventseatlayout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.Column('ticketypeid', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(), nullable=True),
    sa.Column('seats', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ticketypeid'], ['tickettype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventseatlayout_id'), 'eventseatlayout', ['id'], unique=False)
    op.drop_constraint('event_admin_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'datetime')
    op.drop_column('event', 'admin_id')
    op.drop_column('tickettype', 'seated')
    op.drop_column('tickettype', 'limit')
    op.drop_column('tickettype', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickettype', sa.Column('seats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tickettype', sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickettype', sa.Column('seated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_admin_id_fkey', 'event', 'users', ['admin_id'], ['id'])
    op.drop_index(op.f('ix_eventseatlayout_id'), table_name='eventseatlayout')
    op.drop_table('eventseatlayout')
    # ### end Alembic commands ###
