"""added changes to event model

Revision ID: 16a9edc3f8c2
Revises: 5b3625c186ec
Create Date: 2023-05-16 15:53:58.713028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a9edc3f8c2'
down_revision = '5b3625c186ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
