"""Add adminid to Event

Revision ID: 202115ce4d42
Revises: 7c656e25f1b7
Create Date: 2023-05-15 00:44:54.953165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202115ce4d42'
down_revision = '7c656e25f1b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.add_column('event', sa.Column('adminid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'admin', ['adminid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'adminid')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
