"""Add relationship b/w TicketType and EventSeatLayout

Revision ID: 2665eeea5676
Revises: f712342e1f37
Create Date: 2023-05-13 21:47:37.899327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2665eeea5676'
down_revision = 'f712342e1f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventseatlayout', sa.Column('ticketypeid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventseatlayout', 'tickettype', ['ticketypeid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventseatlayout', type_='foreignkey')
    op.drop_column('eventseatlayout', 'ticketypeid')
    # ### end Alembic commands ###
