"""Add Partner Table

Revision ID: 31c66a9e0259
Revises: 6c73fd48143a
Create Date: 2023-05-13 03:45:48.917125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c66a9e0259'
down_revision = '6c73fd48143a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
