"""Commit Message

Revision ID: 39ba4b2c2438
Revises: 401d0fee2c9d
Create Date: 2023-05-14 19:45:45.143684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ba4b2c2438'
down_revision = '401d0fee2c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
