"""Commit Message

Revision ID: 3c00ab6685f4
Revises: e2f7dacaf46d
Create Date: 2023-05-14 15:33:30.070462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c00ab6685f4'
down_revision = 'e2f7dacaf46d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eventseatlayout_id', table_name='eventseatlayout')
    op.drop_table('eventseatlayout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventseatlayout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('eventid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seats', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('ticketypeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['event.id'], name='eventseatlayout_eventid_fkey'),
    sa.ForeignKeyConstraint(['ticketypeid'], ['tickettype.id'], name='eventseatlayout_ticketypeid_fkey'),
    sa.PrimaryKeyConstraint('id', name='eventseatlayout_pkey')
    )
    op.create_index('ix_eventseatlayout_id', 'eventseatlayout', ['id'], unique=False)
    # ### end Alembic commands ###
