"""Commit Message

Revision ID: 3e12af9e6aa1
Revises: 7c1ee36f69f0
Create Date: 2023-05-14 15:09:05.459374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e12af9e6aa1'
down_revision = '7c1ee36f69f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
