"""add modifications

Revision ID: 41a13c569545
Revises: fd74fc9a04fb
Create Date: 2023-05-17 01:07:42.097628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a13c569545'
down_revision = 'fd74fc9a04fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
