"""Add checkedin to UserEventBooking

Revision ID: 459400fcc18b
Revises: 13abbf30cd2a
Create Date: 2023-05-15 14:45:20.202848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459400fcc18b'
down_revision = '13abbf30cd2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('checkedin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usereventbooking', 'checkedin')
    # ### end Alembic commands ###
