"""Commit Message

Revision ID: 464942aca772
Revises: b92fed9c77c7
Create Date: 2023-05-14 19:44:38.828730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464942aca772'
down_revision = 'b92fed9c77c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
