"""Make Venue a property of Event

Revision ID: 4baff26721c9
Revises: d68acd727206
Create Date: 2023-05-11 20:59:08.469802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baff26721c9'
down_revision = 'd68acd727206'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('venue', sa.String(), nullable=True))
    op.drop_constraint('event_venueid_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'venueid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('venueid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_venueid_fkey', 'event', 'venue', ['venueid'], ['id'])
    op.drop_column('event', 'venue')
    # ### end Alembic commands ###
