"""added changes

Revision ID: 5aa723971c26
Revises: f008d5c0413c
Create Date: 2023-05-16 17:00:41.668452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa723971c26'
down_revision = 'f008d5c0413c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
