"""added changes

Revision ID: 5b3625c186ec
Revises: 6a496e7398ab
Create Date: 2023-05-15 17:11:50.425082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3625c186ec'
down_revision = '6a496e7398ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
