"""Commit Message

Revision ID: 5f33a8d1be64
Revises: f87182ab90ec
Create Date: 2023-05-14 15:04:40.432969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f33a8d1be64'
down_revision = 'f87182ab90ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
