"""Commit Message

Revision ID: 67b9033c2f78
Revises: b8bc5b09c6bc
Create Date: 2023-05-14 18:41:34.169594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b9033c2f78'
down_revision = 'b8bc5b09c6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
