"""Commit Message

Revision ID: 680ac930d73e
Revises: 39ba4b2c2438
Create Date: 2023-05-14 20:20:00.564707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ac930d73e'
down_revision = '39ba4b2c2438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('profile', sa.String(), nullable=True))
    op.drop_column('event', 'coverImage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('coverImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'profile')
    # ### end Alembic commands ###
