"""Change UserEventBooking bid to id

Revision ID: 6b20497da0ba
Revises: f9e662bf266e
Create Date: 2023-05-15 01:55:34.469027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b20497da0ba'
down_revision = 'f9e662bf266e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('usereventbooking', 'bid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('bid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('usereventbooking', 'id')
    # ### end Alembic commands ###
