"""Add createdat column to user

Revision ID: 6c73fd48143a
Revises: 8b6d9779fc63
Create Date: 2023-05-11 21:20:03.151835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c73fd48143a'
down_revision = '8b6d9779fc63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('createdat', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'createdat')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
