"""convert foriegnKey in event table in adminid

Revision ID: 6d3590a8908e
Revises: 0c8c14d7ac5c
Create Date: 2023-05-16 20:48:15.342029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3590a8908e'
down_revision = '0c8c14d7ac5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('adminid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'admin', ['adminid'], ['userid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'adminid')
    # ### end Alembic commands ###
