"""Commit Message

Revision ID: 6f45aa16730f
Revises: 9a230c824ec1
Create Date: 2023-05-15 12:57:13.211480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f45aa16730f'
down_revision = '9a230c824ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
