"""Add tickettype to UserEventBooking

Revision ID: 73ef7086a241
Revises: 0e43fe967b36
Create Date: 2023-05-15 01:50:20.104843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ef7086a241'
down_revision = '0e43fe967b36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('tickettype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usereventbooking', 'tickettype')
    # ### end Alembic commands ###
