"""“Second-commit”

Revision ID: 7b9ae9608f47
Revises: f3b55de0d0b3
Create Date: 2023-04-27 04:14:04.145941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9ae9608f47'
down_revision = 'f3b55de0d0b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
