"""Commit Message

Revision ID: 7c1ee36f69f0
Revises: 5f33a8d1be64
Create Date: 2023-05-14 15:08:19.786466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1ee36f69f0'
down_revision = '5f33a8d1be64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickettype', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('tickettype', sa.Column('seated', sa.Boolean(), nullable=True))
    op.add_column('tickettype', sa.Column('seats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickettype', 'seats')
    op.drop_column('tickettype', 'seated')
    op.drop_column('tickettype', 'limit')
    # ### end Alembic commands ###
