"""Commit Message

Revision ID: 81235e3229d8
Revises: db9ff922840e
Create Date: 2023-05-14 13:31:50.472038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81235e3229d8'
down_revision = 'db9ff922840e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
