"""Remove events relationship from the Venue table

Revision ID: 836345177d41
Revises: 4baff26721c9
Create Date: 2023-05-11 21:00:05.188496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836345177d41'
down_revision = '4baff26721c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
