"""Add active to admin

Revision ID: 872fbeee0e3e
Revises: badbcc7bcea8
Create Date: 2023-05-22 22:49:24.693338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872fbeee0e3e'
down_revision = 'badbcc7bcea8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'active')
    # ### end Alembic commands ###
