"""Add relationship between User and UserEventBooking

Revision ID: 907141a07288
Revises: 46720304a0b4
Create Date: 2023-05-10 22:00:44.214064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907141a07288'
down_revision = '46720304a0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
