"""Commit Message

Revision ID: 9a230c824ec1
Revises: 680ac930d73e
Create Date: 2023-05-15 12:43:32.869469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a230c824ec1'
down_revision = '680ac930d73e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
