"""Revert previous change

Revision ID: a8218a47798b
Revises: c62076496eae
Create Date: 2023-05-14 23:47:19.157242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8218a47798b'
down_revision = 'c62076496eae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('usereventbooking', 'eid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('eid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('usereventbooking', 'id')
    # ### end Alembic commands ###
