"""Remove relationship from User

Revision ID: a8bfd9164bf1
Revises: 907141a07288
Create Date: 2023-05-10 22:32:17.155201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bfd9164bf1'
down_revision = '907141a07288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
