"""Commit Message

Revision ID: b8bc5b09c6bc
Revises: 3c00ab6685f4
Create Date: 2023-05-14 18:17:27.242937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bc5b09c6bc'
down_revision = '3c00ab6685f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
