"""Add EventSeatLayout

Revision ID: bc909dc94e2e
Revises: 6c73fd48143a
Create Date: 2023-05-13 21:37:34.714198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc909dc94e2e'
down_revision = '6c73fd48143a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventseatlayout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(), nullable=True),
    sa.Column('seats', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventseatlayout_id'), 'eventseatlayout', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventseatlayout_id'), table_name='eventseatlayout')
    op.drop_table('eventseatlayout')
    # ### end Alembic commands ###
