"""“seventh-commit”

Revision ID: bec0cce7753a
Revises: d92f9518130f
Create Date: 2023-04-27 05:55:10.836517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec0cce7753a'
down_revision = 'd92f9518130f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
