"""Change UserEventBooking id type to UUID

Revision ID: c6220f501bbd
Revises: 2665eeea5676
Create Date: 2023-05-14 23:18:45.762693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6220f501bbd'
down_revision = '2665eeea5676'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usereventbooking_id', table_name='usereventbooking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usereventbooking_id', 'usereventbooking', ['id'], unique=False)
    # ### end Alembic commands ###
