"""“Fourth-commit”

Revision ID: c8048f87193c
Revises: 34ecea15989c
Create Date: 2023-04-27 04:18:51.970427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8048f87193c'
down_revision = '34ecea15989c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
