"""added capacity to event

Revision ID: cf87f784079a
Revises: 81ce5c53e91d
Create Date: 2023-05-16 23:48:08.389827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf87f784079a'
down_revision = '81ce5c53e91d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
