"""Commit Message

Revision ID: d11a2c73c7a8
Revises: 2665eeea5676
Create Date: 2023-05-14 15:00:25.711166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11a2c73c7a8'
down_revision = '2665eeea5676'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
