"""Change UserEventBooking id type to UUID

Revision ID: d37ca7bf94ff
Revises: c6220f501bbd
Create Date: 2023-05-14 23:41:37.371876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37ca7bf94ff'
down_revision = 'c6220f501bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
