"""Change price data type to float in UserEventBooking

Revision ID: d68acd727206
Revises: e85f6f52dade
Create Date: 2023-05-10 22:44:36.718625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68acd727206'
down_revision = 'e85f6f52dade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
