"""added changes to event model

Revision ID: d6e5a8907ec6
Revises: 16a9edc3f8c2
Create Date: 2023-05-16 15:54:07.215639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e5a8907ec6'
down_revision = '16a9edc3f8c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
