"""Add default memebership length for admins

Revision ID: d842253b87f2
Revises: f1a0306ccaa9
Create Date: 2023-05-18 20:40:42.699874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd842253b87f2'
down_revision = 'f1a0306ccaa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
