"""“six-commit”

Revision ID: d92f9518130f
Revises: dc11ce41759c
Create Date: 2023-04-27 05:24:25.540907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92f9518130f'
down_revision = 'dc11ce41759c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickettype', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickettype', 'name')
    # ### end Alembic commands ###
