"""Commit Message

Revision ID: daf4f57ecdb5
Revises: 67b9033c2f78
Create Date: 2023-05-14 19:36:39.986243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf4f57ecdb5'
down_revision = '67b9033c2f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'admin_id')
    # ### end Alembic commands ###
