"""Commit Message

Revision ID: db9ff922840e
Revises: 132718f75162
Create Date: 2023-05-14 13:26:21.870601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9ff922840e'
down_revision = '132718f75162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('coverImage', sa.String(), nullable=True))
    op.add_column('event', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('event', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'time')
    op.drop_column('event', 'date')
    op.drop_column('event', 'coverImage')
    # ### end Alembic commands ###
