"""“Fifth-commit”

Revision ID: dc11ce41759c
Revises: c8048f87193c
Create Date: 2023-04-27 04:56:03.033246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc11ce41759c'
down_revision = 'c8048f87193c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'profile')
    # ### end Alembic commands ###
