"""Commit Message

Revision ID: e2f7dacaf46d
Revises: 3e12af9e6aa1
Create Date: 2023-05-14 15:25:23.665968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f7dacaf46d'
down_revision = '3e12af9e6aa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
