"""Add bookings relationship back to User

Revision ID: e85f6f52dade
Revises: 08c3fb51c857
Create Date: 2023-05-10 22:34:09.292836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85f6f52dade'
down_revision = '08c3fb51c857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
