"""added changes

Revision ID: f008d5c0413c
Revises: a3aa33dc5b80
Create Date: 2023-05-16 17:00:34.718649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f008d5c0413c'
down_revision = 'a3aa33dc5b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
