"""Add membership to admin table

Revision ID: f1a0306ccaa9
Revises: 6d3590a8908e
Create Date: 2023-05-18 20:32:44.867084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a0306ccaa9'
down_revision = '6d3590a8908e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('membership', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'membership')
    # ### end Alembic commands ###
