"""Add relationship b/w Event and EventSeatLayout

Revision ID: f712342e1f37
Revises: bc909dc94e2e
Create Date: 2023-05-13 21:39:19.125334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f712342e1f37'
down_revision = 'bc909dc94e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
