"""Commit Message

Revision ID: f87182ab90ec
Revises: d11a2c73c7a8
Create Date: 2023-05-14 15:03:48.565547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87182ab90ec'
down_revision = 'd11a2c73c7a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('coverImage', sa.String(), nullable=True))
    op.add_column('event', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('event', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'datetime')
    op.drop_column('event', 'coverImage')
    # ### end Alembic commands ###
