"""Change UserEventBooking id to bid

Revision ID: f9e662bf266e
Revises: 73ef7086a241
Create Date: 2023-05-15 01:55:21.536076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e662bf266e'
down_revision = '73ef7086a241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('bid', sa.UUID(), nullable=False))
    op.drop_column('usereventbooking', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usereventbooking', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('usereventbooking', 'bid')
    # ### end Alembic commands ###
